### ISSUE TITLE
What is the type of this application?

### ISSUE THREAD

**Issue by alexya** [michaelpittino/QuickSkin#1]
I tried to build it, but I got the error. 
```
1>LINK : fatal error LNK1561: entry point must be defined
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

and I checked the functions in main.cpp, there is no `main` or `winmain`, there is a `DllMain`. 
So, how can I build it? I google the error above, it told me to select SubSystem in Linker->System, e.g. 
![image](https://user-images.githubusercontent.com/2831220/34905631-17f0fcf8-f898-11e7-8e66-d10184fd8dc1.png)

**Comment by alexya** [comment]
I fixed it by selecting "Windows" from the dropdown list box and change configuration from `release` to `debug`.
But the question is the output is a QuickSkin.dll, how can I use it? put it under the same folder of lol.exe?

**Comment by michaelpittino** [comment]
I can see on your screenshot that you have the `Release` configuration selected.
Actually I have only set the settings for debug. So I'd suggest you just build it with the debug configuration.
The entrypoint error is related to the `Configurationtype` setting on the `Configuration Properties > General` page. You need to change it from `Application (.exe)` to `Dynamic Library (.dll)`.

But please note that this project won't work anymore, since it was build for patch 7.24.
See: https://www.unknowncheats.me/forum/1966944-post7.html

Edit: I've updated the README to indicate that this project is outdated.

**Comment by alexya** [comment]
git it, thx. T_T
